### ISSUE TITLE
plot several lines at the same time 

### ISSUE THREAD

**Issue by carlomontec** [Evizero/UnicodePlots.jl#105]
Hi, 
just a suggestion of usability. It would be great to being able to plot several lines at the same time, receiving a Matrix in which each column is a line. 
Thank you this great package.

**Comment by tuckertranslator** [comment]
Seconding this, as it would be awesome. @carlomontec any thoughts on maybe collaborating on a pull request for adding this ability?

**Comment by colinxs** [comment]
Unfortunately this fails to update the axis limits:

![uni](https://user-images.githubusercontent.com/18266472/73813584-44e85f00-4795-11ea-92c5-d38dbe6e0c29.png)

**Comment by Evizero** [comment]
Correct. You could try using Plots.jl with the `unicodeplots()` backend to achieve what you are trying to do
