### ISSUE TITLE
UnicodePlots is the spice of ProgressMeter's life

### ISSUE THREAD

**Issue by mmattocks** [Evizero/UnicodePlots.jl#107]
This package is extremely good. I have been using it extensively to monitor the progress of distributed long-running optimisations by showing plots in ProgressMeter updates. I intend to use it in the future to communicate with my boss about routine results that I don't want to bother with pyplot for and am seriously considering using it for several figures of my PhD thesis. Thanks for your work on it!
![screenshot](https://user-images.githubusercontent.com/28366182/69361258-1a890a00-0c5a-11ea-9a81-1382e7f30522.png)

**Comment by Evizero** [comment]
Thank you for the kind words! They are appreciated. I am glad to hear you put the package to good use
