### ISSUE TITLE
Lineplot border out of whack

### ISSUE THREAD

**Issue by tuckertranslator** [Evizero/UnicodePlots.jl#108]
Hi there. I am using IJulia interface (Julia 1.1.1). When I make plots, the borders are out of line. Not sure how to address the issue. 
![Captura de pantalla 2019-11-27 a las 10 08 18](https://user-images.githubusercontent.com/26937470/69750467-b35bd180-1101-11ea-9759-5c3051367d39.png)

**Comment by Evizero** [comment]
see https://github.com/Evizero/UnicodePlots.jl/issues/9

**Comment by tuckertranslator** [comment]
@Evizero thanks. The border=:dotted trick worked.
