### ISSUE TITLE
heatmap does not show colors if I run an script outside REPL

### ISSUE THREAD

**Issue by ronisbr** [Evizero/UnicodePlots.jl#111]
Consider the following script:

```julia
using UnicodePlots

println(IOContext(stdout, :color=>true),lineplot([-1,+1],[-1,+1], color = :red))
println(IOContext(stdout, :color=>true),heatmap(repeat(collect(0:10)', outer=(11, 1)), zlabel="z"))
```

If I open Julia and run this from REPL using `include`, then I get what I expect:

<img width="366" alt="Captura de Tela 2020-02-02 às 19 24 17" src="https://user-images.githubusercontent.com/1068295/73616401-9ce66080-45f1-11ea-9087-9185e1120986.png">

However, if I run directly from the command line like `julia script.jl`, then I get this:

<img width="364" alt="Captura de Tela 2020-02-02 às 19 24 58" src="https://user-images.githubusercontent.com/1068295/73616418-b4bde480-45f1-11ea-9f7c-d0dcc4106cb4.png">

The color works in `lineplot` but not at `heatmap`.

**Comment by ronisbr** [comment]
The source of the "problem" is `Crayons`. If I start the script using `julia --color=yes` then it works.

**Comment by DrDaleks** [comment]
fwiw, not reproducible on zsh@{iTerm|Terminal}@macOS (no need for the extra color option)

**Comment by ronisbr** [comment]
Yes! It is working with Julia 1.7. I will close, thanks for letting me know @DrDaleks !
