### ISSUE TITLE
wrong ylim when using Float32?

### ISSUE THREAD

**Issue by colinxs** [Evizero/UnicodePlots.jl#113]
Not sure what's going on here but I'm seeing some strange behavior when using a Float32 ylimits:
![unicodeplots](https://user-images.githubusercontent.com/18266472/73809283-9c7fce00-4787-11ea-8397-20841d1f7031.png)

**Comment by t-bltg** [comment]
Fixed, as a consequence of https://github.com/Evizero/UnicodePlots.jl/pull/147.
