### ISSUE TITLE
Plots side by side?

### ISSUE THREAD

**Issue by ngiann** [Evizero/UnicodePlots.jl#116]
Thanks for this amazing package which allows me to do a lot of work on remote computers.

Is it possible to have two plots displayed side by side, as opposed to one over the other?

I have tried something naive like:
`[barplot(randn(10)) barplot(randn(10))]`

but it won't do the trick.
Many thanks

**Comment by dpo** [comment]
I would also love to be able to do the same, without pulling in Plots.jl.

**Comment by ngiann** [comment]
Is this an option using Plots.jl? I didn't realize, good tip! Thanks.

Dominique <notifications@github.com> schrieb am So., 10. Mai 2020, 16:48:

**Comment by Evizero** [comment]
That is not implemented right now.

**Comment by ngiann** [comment]
thanks for your reply.

**Comment by t-bltg** [comment]
Will be closed by https://github.com/JuliaPlots/Plots.jl/pull/3787.
