### ISSUE TITLE
Example for UnicodePlots in backends is broken

### ISSUE THREAD

**Issue by melonedo** [Evizero/UnicodePlots.jl#118]
In the manual/backends section, the example 
```@example backends
unicodeplots()
plot([sin cos])
```
could not run, Julia 1.4.0 errors:
```
ERROR: MethodError: no method matching unzip(::Array{Tuple{Array{Float64,1},Array{Float64,1}},2})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
```
I tried `plot([sin;cos])` and it works as expected. 

Also, UnicodePlots is probably tuned for monospace fonts, and it uses colors, so I guess a screenshot instead of simply pasting the result would be better.
![image](https://user-images.githubusercontent.com/44501064/79525404-5dc69800-8095-11ea-8503-7b7690a3e1d8.png)

**Comment by Evizero** [comment]
looks like a Plots.jl issue
