### ISSUE TITLE
Move to JuliaPlots?

### ISSUE THREAD

**Issue by BeastyBlacksmith** [Evizero/UnicodePlots.jl#123]
@Evizero do you think it would be a good idea to move this to JuliaPlots to help out with maintenance?

**Comment by Evizero** [comment]
In my experience moving a package doesn't really create new contributors. Thats said, I have to admit this is the one package I have a hard time parting from. 

I would very much welcome assistance though

**Comment by mmattocks** [comment]
I use UnicodePlots and Plots for entirely different things. I would personally prefer not to have to add Plots for every algorithm I monitor on-line with UnicodePlots.

**Comment by BeastyBlacksmith** [comment]
That wasn't the intention. We were talking about the `JuliaPlots` github organization and not `Plots.jl` (where it is a backend already).

Anyway it seems to me, things are fine as they are and if there is something I can help with, feel free to ping me. I am closing this.
