### ISSUE TITLE
Boxplots

### ISSUE THREAD

**Issue by Evizero** [Evizero/UnicodePlots.jl#13]
Since my main use-case for Julia right now is simulation/optimization and I still do my data analysis in R, I don't really need a boxplot in Julia. 

That being said, I am very intrigued to implement one simply because there are perfect Unicode signs available to do this (they wouldn't even have a gap between the lines like they do here)

```
──┬──
  │
┌─┴─┐
│   │
├───┤
│   │
└─┬─┘
  │
──┴──
```

The only issue I guess would be scale. Alternatively one could use simply the `BrailleCanvas` and draw lines, which would offer a better resolution.

Does anyone have an opinion on boxplots?

**Comment by waldyrious** [comment]
As I see it, terminal plotting is mostly useful for getting quick visualizations out of data, so it should be fine if proportions are eyeballed. It's not like one would measure the height of a plot to obtain a value, so as long as relative differences are preserved (and proportionality as well, however possible/viable), it should be fine, IMO. I'd treat any incorrections (i.e. lines at same height that should really be slightly offset) as expected quantization errors due to the size of the "pixels".

**Comment by Evizero** [comment]
Good point! I guess I could "force" a minimal row count according to the requirements needed to keep quantization errors below some threshold. Also, if I do sit down and implement them I want to have grouped box-plots, which isn't that much of extra work anyhow

It will have to wait a little, however, I need to spend some time on my ML framework. I do have deadlines :-)

**Comment by equinaut** [comment]
If this is still in the pipeline I'd love to see it! I use this module all the time for quick visuals, and sometimes I'll lean on it entirely for the fast and simple analysis. When I'm using unicode to plot my data high precision just isn't a concern, all I'm looking for is a general idea of what it looks like without expending much effort. In my opinion boxplots would add a lot of value to this package - it'd be a nice complement to the histogram.

**Comment by tbreloff** [comment]
It's not perfect, but:

<img width="542" alt="screen shot 2016-12-08 at 8 22 36 am" src="https://cloud.githubusercontent.com/assets/933338/21001272/b37e2dc2-bd1f-11e6-8515-c76708df45e3.png">

**Comment by Evizero** [comment]
Hi! Glad to hear UnicodePlots is useful to you!
It still is in the pipeline, but I have other things on the agenda before my intended refactor. So it might be a little while

**Comment by Evizero** [comment]
closed by @mgtlake in #84 🎉
