### ISSUE TITLE
"pre" stairs plot

### ISSUE THREAD

**Issue by dpo** [Evizero/UnicodePlots.jl#16]
It's useful to have different styles of stair plots. Here's a variant where the step occurs before the next point:

```diff
diff --git a/src/scatterplot.jl b/src/scatterplot.jl
index 44ed684..888cac9 100644
--- a/src/scatterplot.jl
+++ b/src/scatterplot.jl
@@ -113,6 +113,27 @@ function stairs!{T<:Canvas,F<:Real,R<:Real}(plot::Plot{T}, X::Vector{F}, Y::Vect
   lineplot!(plot, xVec, yVec; args...)
 end
 
+function stairs_pre!{T<:Canvas,F<:Real,R<:Real}(plot::Plot{T}, X::Vector{F}, Y::Vector{R}; args...)
+  xVec = zeros(length(X) * 2 - 1)
+  yVec = zeros(length(X) * 2 - 1)
+  xVec[1] = X[1]
+  yVec[1] = Y[1]
+  o = 0
+  for i = 2:(length(X))
+    xVec[i + o] = X[i-1]
+    xVec[i + o + 1] = X[i]
+    yVec[i + o] = Y[i]
+    yVec[i + o + 1] = Y[i]
+    o += 1
+  end
+  lineplot!(plot, xVec, yVec; args...)
+end
+
+
 function stairs{F<:Real,R<:Real}(X::Vector{F},Y::Vector{R}; args...)
   xVec = zeros(length(X) * 2 - 1)
   yVec = zeros(length(X) * 2 - 1)
```

**Comment by Evizero** [comment]
Thanks! I can add that if you need it. What's the use case though?

**Comment by dpo** [comment]
Most libraries give access to different step styles (e.g., Gnuplot, Matlab, Matplotlib, ...) For instance: http://matplotlib.org/api/lines_api.html#matplotlib.lines.Line2D.set_drawstyle

My personal use-case is performance profiles (a way to compare the performance of various solvers on a common test set).

**Comment by Evizero** [comment]
I added it into the current master. You can change the style using the style parameter. At the moment it allows for `:pre` and `:post` but in the future `:mid` might also be possible

```Julia
stairs([1, 2, 4, 7, 8], [1, 3, 4, 2, 7], color = :red, style=:pre)
```

**Comment by dpo** [comment]
Excellent. Thanks much!
