### ISSUE TITLE
how to save as PNG?

### ISSUE THREAD

**Issue by tbreloff** [Evizero/UnicodePlots.jl#19]
I'm starting to look through this package for implementation in [Plots.jl](https://github.com/tbreloff/Plots.jl), but I can't figure out how you created the PNG files.  Did you do that by hand?  Any ideas of how to automate?

**Comment by tbreloff** [comment]
I'm basically done implementing this in Plots.jl, just need the `savepng` method and I can produce the examples markdown similar to https://github.com/tbreloff/Plots.jl/blob/master/docs/qwt_examples.md.

If you're curious about any of the implementation, check out: https://github.com/tbreloff/Plots.jl/blob/dev/src/backends/unicodeplots.jl

**Comment by Evizero** [comment]
There is no way currently to produce images from Unicode Plots. Frankly, I don't plan on coming up with one as I don't see the use case (except to produce documentation, which I admit would be nice).

**Comment by tbreloff** [comment]
Check out [the examples](https://github.com/tbreloff/Plots.jl/blob/dev/docs/unicodeplots_examples.md)!

If you want to see what I did, check out `savepng` [here](https://github.com/tbreloff/Plots.jl/blob/dev/src/backends/unicodeplots.jl).

**Comment by Evizero** [comment]
Cool!

.. I'll fix that limit rounding issue

**Comment by waldyrious** [comment]
I think the natural export format for UnicodePlots.jl should be `*.txt`. Maybe implement a convenience `save()` function that does this to spare the select/copy/paste/save workflow that would otherwise be needed? Not that the exported graphs would be very useful anyway, but it seems too much of a natural fit not to do :)

**Comment by Evizero** [comment]
I have been think about that before. I didn't do it in the end, because even with gedit I found myself unable to force a monospace rendering of the text. it just never looks the way it does in the terminal, no matter what font I use. This annoys the heck out of me

**Comment by Evizero** [comment]
Also, if I do want to store the output, I actually only use it the same way I use `println` in the sense that I just redirect STDOUT.

After all, my motivation for implementing UnicodePlots in the first place, was to have more useful terminal output.

That being said, if you would actually like to have a save function to store the text-output, then I will implement one

**Comment by waldyrious** [comment]
I don't think it's necessary, just kinda makes sense (and if Plots.jl ends up implementing a generic `save()` funcion, this would be a more appropriate solution for UnicodePlots.jl rather than doing nothing or applying an OSX-only hack)

**Comment by Evizero** [comment]
sure, makes sense

**Comment by tbreloff** [comment]
> and if Plots.jl ends up implementing a generic save() funcion

What did you have in mind?  Want to start an issue?

**Comment by waldyrious** [comment]
>> and if Plots.jl ends up implementing a generic save() funcion

> What did you have in mind? Want to start an issue?

Oh, nothing in particular, it just seems to me to be much in line with the philosophy of Plots.jl, i.e. generic methods that adapt to the backend, or in this case, the output format -- so that you might have something like `save(plot, format="png")` rather than `savepng()`, `savetxt()`, `savesvg()`, and so on. If you like the idea, I can open an issue in Plots.jl :)

**Comment by tbreloff** [comment]
Sure open an issue... of course it would probably be easiest to have a save
method which looks at the file extension and figures it out.
