### ISSUE TITLE
Integrate with TerminalUI.jl

### ISSUE THREAD

**Issue by Keno** [Evizero/UnicodePlots.jl#2]
I've been working on a general framework for building Terminal uis over at https://github.com/Keno/TerminalUI.jl. I'm mostly opening an issue here as an FYI,
since I don't know when I'll find the time to do the integration and TerminalUI is still very
much early alpha, but figured you may be interested, esp. since some of its terminal
features may come in handy for you.

**Comment by Evizero** [comment]
That is a cool idea! We should definitively keep each other in mind, especially for design discussions and feedback.

For now, I think the best way to make progress is to simply see where our roads are leading and refactor when we see clear patterns emerging. Unicode opens a lot of unexpected doors when it comes to the terminal and I think we have only scratched the surface!

**Comment by Keno** [comment]
Sure, I just wanted to make you aware of my package, in case you want to start adding things like mouse support or scrolling or some such, which I already have over there.

**Comment by Evizero** [comment]
Well this open doors to ideas that I did not know exist. What would be great is a little documentation in your readme, even if it just mentioned what you can do with it and what parts of code to look at for that

One thing I want to tackle soon is animation by cursor movement and overwriting, which I saw at [ProgressMeter.jl](https://github.com/timholy/ProgressMeter.jl), but as far as I am able to tell that is very trivial to do.

**Comment by Keno** [comment]
Yes, you're right. I need to step back and write some documentation.

**Comment by Evizero** [comment]
What I think could be useful for you is the BrailleCanvas. I'll document it in a little more detail, but basically it is just the pixel-canvas without decorations and with a drawRow() method you can decide which row of the canvas to print, which means you embed it anywhere. Basically it enables you to have a rectangular pixel-grid where you can manipulate each pixel

**Comment by Evizero** [comment]
I'll close this for now. We can always resume the conversation further down the road
