### ISSUE TITLE
Support Colors.Colorant

### ISSUE THREAD

**Issue by tbreloff** [Evizero/UnicodePlots.jl#20]
Would be nice if you could set any color using RGB from Colors.jl (or just accepting a tuple of (R,G,B)?)

**Comment by Evizero** [comment]
I have been thinking about that. I have to try how simple it is to use other colors than the one that `print_with_color` supports. What I don't really want to do, is force the user to make config changes outside of Julia to get UnicodePlots to run properly, but maybe there is some middle ground.

I admit it would be pretty nice for a lot of things to have more than just the ~ 5 colors. I'll look into it
