### ISSUE TITLE
Make parameters xlim and ylim a little less precise

### ISSUE THREAD

**Issue by Evizero** [Evizero/UnicodePlots.jl#21]
Related to https://github.com/Evizero/UnicodePlots.jl/issues/19 . 
When specifying a plot with xlim=[minimum(x),maximum(x)] for example, make sure that the limits won't end up being something like [0.3343223244234, 9.9352534323232432]

**Comment by Evizero** [comment]
This is fixed in master and I will tag it now. As soon as this is tagged you should probably try to redo the UnicodePlots documentation to get rid of the ugly floating point labels @tbreloff

**Comment by tbreloff** [comment]
No problem... I like that it bugged you :)

**Comment by tbreloff** [comment]
I'd like to reopen this one, if you don't mind.  It seems like you fixed the "lots of decimals of precision displayed" problem, but created a more subtle issue which makes the range much too big if near a threshold value.  See:

```
      ┌────────────────────────────────────────────────────────────┐
    1 │⠙⡄⠀⢰⠉⢣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠊⢱⠀⠀⡰⠉⢣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ y_1
      │⠀⢱⢠⠃⠀⠀⢇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠇⠀⠀⢣⢠⠃⠀⠈⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ y_2
      │⠀⠀⡿⠀⠀⠀⢸⡀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠘⡎⠀⠀⠀⢹⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⣷⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⢠⢇⠀⠀⠀⠈⡆⠀⠀⠀⠀⠀⠀⠀⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⢸⠘⡄⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⢰⠁⠀⠀⠀⡸⢸⠀⠀⠀⠀⢣⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⡎⠀⡇⠀⠀⠀⠈⡆⠀⠀⠀⠀⠀⠀⡸⠀⠀⠀⠀⡇⠈⡆⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⢀⠇⠀⢸⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⢰⠁⠀⢣⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⢸⠀⠀⠸⡀⠀⠀⠀⢸⠀⠀⠀⠀⠀⢰⠁⠀⠀⠀⡸⠀⠀⢸⠀⠀⠀⠀⢣⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⡜⠀⠀⠀⡇⠀⠀⠀⠘⡄⠀⠀⠀⠀⢸⠀⠀⠀⠀⡇⠀⠀⠈⡇⠀⠀⠀⢸⠀⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⡇⠀⠀⠀⢱⠀⠀⠀⠀⡇⠀⠀⠀⠀⡇⠀⠀⠀⢠⠃⠀⠀⠀⢇⠀⠀⠀⠀⡇⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠉⠉⠉⠉⢹⠉⠉⠉⠉⢹⠉⠉⠉⢩⠋⠉⠉⠉⢹⠉⠉⠉⠉⢹⠉⠉⠉⠉⢏⠉⠉⠉⢹⠉⠉⠉⠉⡹⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠁│
      │⠀⠀⠀⠀⠀⡇⠀⠀⠀⢸⠀⠀⠀⢸⠀⠀⠀⠀⡎⠀⠀⠀⠀⠘⡄⠀⠀⠀⢸⠀⠀⠀⡜⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⢇⠀⠀⠀⠀⡇⠀⠀⡇⠀⠀⠀⢀⠇⠀⠀⠀⠀⠀⡇⠀⠀⠀⠘⡄⠀⠀⡇⠀⠀⠀⢰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⢣⠀⢀⠇⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⡇⠀⢰⠁⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⢸⠀⢸⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠘⡄⠀⠀⠀⢸⠀⡸⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠀⢇⠀⠀⠀⠀⡇⡇⠀⠀⠀⢀⠇⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠘⡄⡇⠀⠀⠀⢰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠀⢸⡀⠀⠀⠀⢳⠃⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⢿⠀⠀⠀⠀⡸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⡸⡄⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠈⡆⠀⠀⠀⡼⡀⠀⠀⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      │⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⢠⠃⢣⠀⠀⡸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢱⠀⠀⢠⠃⢇⠀⠀⡸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
   -1 │⠀⠀⠀⠀⠀⠀⠀⠀⢣⣀⠎⠀⠀⢇⣠⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢇⣀⠎⠀⠘⢄⡠⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
      └────────────────────────────────────────────────────────────┘
      0                                                           20
```

It seems like you have big, fixed ranges, and just pick the smallest range that fits all the data.  This works but ends up with lots of emptiness in many cases.  A simpler solution might be to keep what you had before and just round/truncate the precision that is shown based on the numbers.  Thoughts?

**Comment by Evizero** [comment]
Well here is the issue. I have to round based somewhat on the difference of an axis. if my plot ranges from 0.0001 to 0.0005 then rounding cant be to the next integer.; the same with really large numbers.

That being said, I haven't found a solution that I am totally happy yet, so I am absolutely open to suggestions and PRs in that regard

**Comment by tbreloff** [comment]
Ok I may do a PR, or maybe just throw some example code here.  Thanks

**Comment by Evizero** [comment]
This should be better now if you specify `xlim` or `ylim` accordingly (which AFAIK you allways do in Plots). Let me know what you think

**Comment by tbreloff** [comment]
Cool I'll check it out. Did you use a known algo, or your own?

**Comment by Evizero** [comment]
thanks. no, it's a pretty simple hack

**Comment by Evizero** [comment]
I am closing this for now. If you feel this is unresolved please reopen it

**Comment by Sacha0** [comment]
Is the `xlim` integer clamping shown below related? Thanks for the fantastic package!
```julia
julia> scatterplot([0.0, pi/3, 2pi/3, pi], [0.0, 0.25, 0.50, 0.75], xlim = [0.0, pi + 0.1])
       ┌────────────────────────────────────────┐
   0.8 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
     0 │⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
       └────────────────────────────────────────┘
       0                                        4
```

**Comment by Evizero** [comment]
Yes I suppose. The thing is that with Unicode characters one can only offer so much resolution, so I made the decision to give the clear appearance of approximation (a xlim label of 3.24159 would give the wrong impression of how much granularity this visualisation has to offer)

Anyway I will probably aggressively refactor this package soon and may may use of Tom's PlotUtils for tick calculation. Have not looked into that package yet
