### ISSUE TITLE
Base on Compose.jl

### ISSUE THREAD

**Issue by Evizero** [Evizero/UnicodePlots.jl#27]
So I have been thinking about automatic plot-resizing that stretches the size of the terminal (similar to how large arrays are printed in the REPL). To achieve this I would have to store the data to be drawn and delay the actual drawing on the canvas until show is called. This would enable all kinds of cool things though, such as being able to resize the "virtual space" of the plot when new data is added onto it. 

If I were to do this refactoring, it would make sense to base this package on [Compose.jl](https://github.com/dcjones/Compose.jl) (I think). I don't believe the API of UnicodePlots would change that much (if at all), but the compile-time would probably increase.

I wouldn't do this big refactoring right away, but I thought I'd ask around what people think about this.

Does anyone have an opinion on this?

**Comment by tbreloff** [comment]
FYI... this is how I currently do it in Plots.  I build/save everything I
need about the plot and draw it all at once on display.

On Tue, Sep 22, 2015 at 11:36 AM, Christof Stocker <notifications@github.com

**Comment by Evizero** [comment]
so what's your impression of that approach? does it feel responsive? I really want to keep this package as efficient as I can

**Comment by tbreloff** [comment]
For the plots I've been doing, it's pretty much written to the screen
before I release the enter key... so I'd say it's good enough for many
cases ;)

On Tue, Sep 22, 2015 at 12:51 PM, Christof Stocker <notifications@github.com

**Comment by jakebolewski** [comment]
Although I'm partial to keeping the dependencies lightweight (as a great plotting package of last resort) I must confess that I also want to see how far you can push the functionality of this package :-)

**Comment by tbreloff** [comment]
Well making Compose a dependency is pretty much the last thing you want to do if you're trying to stay lightweight.  I'm actually not totally sure why you think Compose would help, though. 

If you're willing to interface through Plots (which only requires Colors and Reexport), I've got a lot of the framework ready to go.  I think all that is needed is some method which will give you the terminal's current width/height in characters, and with a couple lines of code you could do this in Plots.  Does this method exist?  I guess it must if the array printing code expands to the size of the terminal already...

One extra bonus of going through Plots is that I have hacky support for subplots... with a little TLC we could lay out the subplots in a grid using this resizing logic.

If you don't want to depend on Plots, that's cool.  Just look at https://github.com/tbreloff/Plots.jl/blob/master/src/backends/unicodeplots.jl#L27-L61 and copy what you need.

**Comment by Evizero** [comment]
Well, I don't know actually if Compose is helpful for what I have in mind (I didn't spend much time researching this as I am very preoccupied with SVMs currently). 

Basically, I am considering buffering the data and thus compute the canvas only on `show`, which would allow changing the plotsize and plotlimits even after the plot is defined. This in turn would allow me to stretch the plot (if Julia is in interactive-mode) to the whole terminal when `show` is called

**Comment by Evizero** [comment]
I'll close this. We should rethink a discussion once the package reaches full maturity
