### ISSUE TITLE
UnicodePlots with Emacs ESS

### ISSUE THREAD

**Issue by datafig** [Evizero/UnicodePlots.jl#31]
First of all thanks for a great library. I have been trying to get the library to work inside Emacs. Unfortunately the graphs are not legible with the exception of bar plot. Any suggestion if it would be possible to make the library work inside of Emacs.

<img width="498" alt="unicode_plot" src="https://cloud.githubusercontent.com/assets/12907357/10179709/a0636456-66bc-11e5-8915-ad6f4c42b652.png">

**Comment by jakebolewski** [comment]
It looks like buggy unicode `charwidth` strikes again

**Comment by Evizero** [comment]
this looks like more than a char-width problem. the plotted points are plain wrong.

I think the font that you are using is not really able to deal with the braille characters that are used to plot the dots. The most promising thing you could try is change the font.

**Comment by datafig** [comment]
I have tried a different font.. Most recently I tried `https://github.com/adobe-fonts/source-code-pro` by defining `(set-face-attribute 'default nil :foundry "apple" :family "Source Code Pro")` in my .emacs but the output is same. 
![screen shot 2015-09-29 at 10 47 26 pm](https://cloud.githubusercontent.com/assets/12907357/10185357/1c273d12-66fc-11e5-9699-c587225584c3.png)

**Comment by Evizero** [comment]
That is strange then. I do know that font is able to display the Braille characters correctly. Seems to be some Emacs specific issue.

You could try switching off features, if possible (such as the syntax highlighting that obviously manipulates the plot output). maybe that helps

**Comment by Evizero** [comment]
I think I came up with a solution from the library side. I'll additionally implement a different canvas based on other unicode signs. The only caveat is that they have only half the resolution on the y axis and as a side-note are a little more involved computationally (but I don't think that will be noticeable).

I think that should provide a more stable solution for various environments. After all the Braille characters seem to receive very little love outside a standard linux terminal environment

**Comment by Evizero** [comment]
I added a new canvas that uses other Unicode signs. So I'll close this issue for now. 

If you are still interested in trying this out do `Pkg.checkout("UnicodePlots")` and add the keyword argument `canvas = BlockCanvas` to the plotting call. 

![spy](https://cloud.githubusercontent.com/assets/10854026/10786536/ff4ce572-7d6a-11e5-8622-9d021f0b9a9e.png)

**Comment by Evizero** [comment]
I also just added an `AsciiCanvas` as a last resort.

**Comment by waldyrious** [comment]
Just wanted to say, the ASCII canvas is seriously cool!

**Comment by Evizero** [comment]
thanks, glad you like it. It's experimental right now, but I'll tweak it over the next weeks
