### ISSUE TITLE
plot in external window

### ISSUE THREAD

**Issue by yakir12** [Evizero/UnicodePlots.jl#33]
It would be cool to send the plots to some other terminal window. This would be useful for some plot that constantly gets updated by some process. This way we can have some basic UI in the current terminal while the resulting plot (that additionally depends on some other continuously updating process) gets updated in the other.

**Comment by Evizero** [comment]
Don't know how feasible that is, but I'll look into it

**Comment by Evizero** [comment]
doesn't really seem like the right direction for this
