### ISSUE TITLE
Support plotting time series

### ISSUE THREAD

**Issue by milktrader** [Evizero/UnicodePlots.jl#36]
Something along the lines of ...
````
function lineplot{T<:TimeType,R<:Real}(X::AbstractVector{T}, Y::AbstractVector{R};
````
This would require importing the `Base.Dates` package.

**Comment by Evizero** [comment]
I'll look into it

**Comment by milktrader** [comment]
Alright, cool. I'm hacking it out in a branch but the only hold up is finding where to change the code to *display* the first and last date. Here's what it looks like:

![screen shot 2015-11-01 at 3 58 49 pm](https://cloud.githubusercontent.com/assets/324836/10871317/8c67c15e-80b1-11e5-808a-8c5b574ac1a7.png)

**Comment by Evizero** [comment]
you mean how to change the annotations on the x-axis? Try `annotate!(myplot, :bl, "left text")`, `annotate!(myplot, :br, "right text")`

**Comment by milktrader** [comment]
Ah, perfect!

![screen shot 2015-11-01 at 4 08 53 pm](https://cloud.githubusercontent.com/assets/324836/10871365/f6f1fbba-80b2-11e5-8728-b86227823bb6.png)

**Comment by Evizero** [comment]
Looks cool! I'm fine with having `Base` dependencies. I'll happily merge/adapt a PR

**Comment by milktrader** [comment]
Alright, I hacked that pic above with TimeSeries dependency but I've got something that just uses Base.Dates (which is preferable for this package) coming in a bit.
