### ISSUE TITLE
Default canvas shows question marks only (windows)

### ISSUE THREAD

**Issue by mmagnuski** [Evizero/UnicodePlots.jl#44]
I guess this is because windows cmd cannot display unicode characters (can it?), but just to let you know, the default canvas looks "questionable" ;)

![unicodeplots_on_windows](https://cloud.githubusercontent.com/assets/8452354/11642697/a198ccc6-9d3f-11e5-93f1-124b387e984e.PNG)

is there any terminal that works with UnicodePlots on windows?

**Comment by Evizero** [comment]
Thanks for posting. Well, the `BrailleCanvas` is a hit or miss thing. The utilized Unicode characters are not widely supported and if they are they are treated very differently from application to application and font to font.

I'm not a windows user, so the best suggestion I can offer is to use a canvas that works for you. Both the `AsciiCanvas` and the `DotCanvas` use only ASCII characters, so they should more or less always work. There is also the `BlockCanvas`, which is Unicode-based, but might be more visually pleasing.

One thing I could do is introduce a way to overwrite the default.

**Comment by Evizero** [comment]
One thing you could try to make the `BrailleCanvas` work is change the font (if cmd has such an option)

**Comment by mmagnuski** [comment]
I tried changing the font (tested all three (!) font options) but all fonts gave some sort of question-mark-plot. `BlockCanvas` doesn't display well too. 
Well, just another reason to stop using Windows :grimacing:
A way to overwrite the default canvas would be very nice! :grinning:

**Comment by tkelman** [comment]
You can try starting Julia inside mintty, see https://github.com/JuliaLang/julia/issues/7267#issuecomment-156490811

mintty has better unicode support by default, and a better selection of fonts you can change to. deja vu sans mono has reasonable unicode coverage.

**Comment by mmagnuski** [comment]
I've had some troubles running mintty and starting Julia under Cygwin gives me errors:
```
stty: standard input: Inappropriate ioctl for device
ERROR: failed process: Process(`stty raw -echo onlcr -ocrnl opost`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:555
```

But I came back to cmder (I have downloaded the mini version hoping it will be faster than full cmder) and the plots work beautifully now!

**Comment by tkelman** [comment]
That should be fixed in 0.4.2.

**Comment by mmagnuski** [comment]
Oh, I didn't notice that you've released 0.4.2 already, cool!

**Comment by Evizero** [comment]
> But I came back to cmder (I have downloaded the mini version hoping it will be faster than full cmder) and the plots work beautifully now!

Could you give a brief summary what exactly you did to fix the problem for you? So that the next person is saved the troubles of figuring it out by him/herself. Was it a specific version of cmder/mintty that you downloaded?

**Comment by mmagnuski** [comment]
I don't think it is because of a specific version of cmder - I didn't use Julia from cmder before, because cmder can be horribly slow sometimes (waiting a few seconds for results of `ls`). So I'd say that generally cmder works well with `UnicodePlots`. 
Concerning mintty - can't say much too; I downloaded mintty and Cygwin but mintty didn't seem to see cygwin on my machine so I went on to cmder.

**Comment by Evizero** [comment]
Thanks! I'll leave this issue open for a bit for others to see
