### ISSUE TITLE
how to set plot background color to contrast with terminal color?

### ISSUE THREAD

**Issue by stardiviner** [Evizero/UnicodePlots.jl#46]
Here is a screenshot which I'm using UnicodePlots with a solarized light color-scheme in Konsole.

![screenshot_20160306_134830](https://cloud.githubusercontent.com/assets/378699/13552511/610f2f9e-e3a1-11e5-9e3a-e1f8bca85dae.png)

**Comment by Evizero** [comment]
There is currently no such concept in UnicodePlots for a plot background color, because the background is basically made up by *spaces* or something equivalently transparent. That means that as it is now the background is simply the terminal background

**Comment by Evizero** [comment]
That said, there is a way to select a background color for a character when writing in a terminal. I don't know if Julia provides a way to specify that, but if there is that would be the way to implement this functionality.

**Comment by stardiviner** [comment]
Thanks. I will temporary use a dark terminal background color.

**Comment by lopezm94** [comment]
It would be nice to be able to choose a color for borders and title for the same reason.

**Comment by Evizero** [comment]
the border and annotation color problem will be fixed by #85
