### ISSUE TITLE
Modify canvas size

### ISSUE THREAD

**Issue by omus** [Evizero/UnicodePlots.jl#48]
I'm not sure how practical this is but I would like it if I could increase the canvas size of a plot.

**Comment by Evizero** [comment]
do you mean after it was created or before? if you mean before then there are the key word parameters  `width` and `height` which should work for most plot commands

**Comment by Evizero** [comment]
If you mean resizing an existing plot, then there is no way to do that currently within UnicodePlots itself. However, I think you can do that in @tbreloff s [Plots.jl](https://github.com/tbreloff/Plots.jl) with the `unicodeplots` backend

**Comment by Evizero** [comment]
I can't really change this current behaviour without a major redesign of how UnicodePlots creates plots. So I am afraid this won't be possible in the near future

**Comment by omus** [comment]
Actually `width` and `height` was what I was after. Sorry, I'm not sure how I managed to miss that.

**Comment by Evizero** [comment]
No problem at all. feel free to ask questions any time.
