### ISSUE TITLE
Pie charts as in filepie

### ISSUE THREAD

**Issue by waldyrious** [Evizero/UnicodePlots.jl#54]
https://github.com/marcodiiga/filepie has an interesting approach to display pie charts in the terminal. They don't look terribly good, due to the resolution, but the approach could be interesting to consider (e.g. as inspiration) for UnicodePlots.

**Comment by Evizero** [comment]
The next refactor will use a similar approach to allow for 256 color canvas with half the resolution as the current BrailleCanvas. This kind of plot would then be possible. I have cool stuff planned. Well I think it's cool stuff anyway. But I can't say when I'll have the time to do it. probably shortly after 0.5 release. Stay tuned!

**Comment by Evizero** [comment]
Not quite sure how much time I would invest into a pie chart though, given how little useful it is in general. But I am guessing that it should be possible through Plots.jl once the refactor of UnicodePlots is done

**Comment by Evizero** [comment]
Other than the readme screenshot this can't really serve as inspiration anyway because of the license

**Comment by waldyrious** [comment]
> Other than the readme screenshot this can't really serve as inspiration anyway because of the license

Damn, you're right, I hadn't noticed. That's too bad :(

**Comment by Evizero** [comment]
I'll close this to avoid license confusion, but I'll think about supporting some kind of Pie chart
