### ISSUE TITLE
Support for 256 colors. 

### ISSUE THREAD

**Issue by KristofferC** [Evizero/UnicodePlots.jl#58]
Newest Julia master allows to use a number as the color and will then print in the corresponding 256 color palette. The argument type for `color` could hence be a bit relaxed if you want.

**Comment by KristofferC** [comment]
For the mixing of colors, perhaps going the 256 color -> RGB -> mix RGB channels -> 256 color could be done.

**Comment by Evizero** [comment]
That sounds interesting. Will explore in my refactor. Currently I am thinking about introducing a custom `ColorType`, which would allow easy conversion for images and the likes
