### ISSUE TITLE
Feature: Histograms

### ISSUE THREAD

**Issue by IainNZ** [Evizero/UnicodePlots.jl#6]
How do you feel about histograms? I'm using this right now:

```julia
function histogram(x, n::Int=5)
    edges, counts = hist(x,n)
    labels = []
    for i in 1:length(counts)
        push!(labels, string("(",edges[i],",",edges[i]+1,"]"))
    end
    barplot(labels,counts)
end
```
```julia
num_over = [1,0,2,1,1,0,2,1,1,0,1,2,2,0,0,2,0,1,1,2,1,1,1,0,1,1,3,1,1,1,2,1,2,0,1,1,0,0,2,1,0,0,1,0,1,1,2,1,1,0,2,0,1,2,1,1,2,2,0,1,0,1,1,2,0,1,1,0,2,1,1,2,0,1,1,1,1,1,0,1,2,1,1,1,2,0,2,1,1,1,2,1,3,1,0,1,2,2,0,2,0,3,2,0,2,0,1,1,3,2,1,2,2,1,1,2,1,1,2,1,2,1,2,2,0,0,0,0,1,2,3,1,0,2,2,2,0,0,1,1,2,1,1,0,0,0,1,1,2,0,2,1,2,1,1,2,2,0,0,2,0,1,2,1,0,2,1,0,1,0,1,1,2,0,2,0,1,1,1,2,1,2,1,2,3,0,1,1,2,1,2,2,0,0,1,1,0,2,0,0,1,0,0,1,0,1,1,0,1,2,0,2,1,1,2,1,2,2,1,0,2,1,0,2,1,1,1,1,1,3,3,0,0,2,2,1,3,1,2,2,1,1,0,0,1,2,2,1,2,2,1,0,2,1,1,2,2,2,1,1,0,0,1,2,1,1,2,1,1,3,2,1,1,1,1,2,1,0,1,1,0,1,1,1,1,1,1,1,3,0,0,1,0,1,0,1,3,0,2,1,1,1,0,3,1,1,1,2,1,1,1,3,1,1,1,2,1,0,0,0,0,2,1,2,2,2,0,2,1,3,1,1,0,3,1,3,2,2,1,2,1,1,1,2,1,1,0,1,0,1,3,0,1,3,1,0,0,2,1,1,0,0,1,1,1,1,1,1,3,2,2,0,1,3,1,1,1,2,0,1,2,1,0,3,0,1,1,2,3,1,1,1,0,2,0,2,1,1,2,2,2,0,2,2,2,2,1,2,2,0,2,3,0,1,1,2,1,0,2,1,2,0,1,1,1,1,1,2,0,0,0,0,1,2,0,3,1,1,1,1,1,0,2,0,0,1,0,1,2,2,1,1,2,0,1,1,2,1,1,1,1,2,0,1,0,1,2,3,1,2,1,0,0,2,2,1,1,2,0,1,1,2,2,2,2,1,0,0,1,2,2,3,0,2,2,2,1,2,1,1,0,1,1,1,2,1,3,1,0,1,1,2,1,1,1,1,0,1,1,1,2,2,1,1,0,2,0,1,0,1,2,0,2,2,1,1,0,2,1,2,2,0,0,1,1,1,1,0,1,2,2,1,1,2,1,2,1,1,0,3,2,1,1,1,1,2,2,1,2,1,1,1,1,1,1,1,1,2,0,0,1,1,3,1,1,1,1,1,2,1,0,1,1,1,0,1,2,2,1,0,1,1,1,0,1,0,1,2,1,1,3,3,0,0,2,2,0,2,2,0,2,1,2,1,1,2,2,0,1,1,1,1,0,2,1,1,0,1,1,1,0,1,2,2,1,1,1,2,3,1,2,2,1,1,1,0,0,2,2,1,1,1,1,2,0,0,1,0,1,3,2,1,1,2,2,1,1,1,2,0,2,1,0,2,0,0,2,3,1,1,2,1,2,1,0,3,1,2,3,1,1,2,3,2,2,1,1,1,1,1,2,0,2,1,0,1,1,2,0,1,1,1,1,1,1,1,3,1,0,0,2,1,1,1,1,1,1,1,1,2,0,2,2,2,2,1,3,1,1,0,0,1,0,2,0,0,1,2,2,0,3,0,0,2,1,1,2,3,1,0,0,2,1,0,0,2,1,1,2,2,3,2,1,1,2,2,2,2,2,1,1,1,0,0,0,0,1,1,2,1,1,1,0,0,1,0,0,1,0,1,0,0,1,2,3,1,1,0,3,0,1,2,0,1,0,2,2,1,2,0,1,1,2,0,2,1,0,0,1,2,0,1,2,1,1,2,0,1,1,0,2,1,1,0,2,2,0,1,1,0,1,0,1,2,2,2,0,1,1,0,1,1,1,0,1,1,2,1,1,0,2,1,1,3,1,0,1,2,3,1,0,3,0,1,0,1,2,1,3,3,1,2,1,1,2,0,3,1,1,2,2,1,1,2,1,1,1,0,0,1,2,1,1,0,3,0,1,1,1,1,2,0,1,2,1,1,1,2,1,1,2,0,0,2,3,0,1,1,2,1,1,1,0,2,1,1,2,1,1,1,2,0,2,1,2,1,2,2,2,2,1,1,0,1,1,2,2,1,1,1,2,1,1,1,2,1,2,0,2,2,1,1,2,0,1,0,2,2,0,2]
histogram(num_over)
```
```
             ┌─────────────────────────────────────────────┐
   (-1.0,0.0]│▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ 221                      │
    (0.0,1.0]│▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ 460 │
    (1.0,2.0]│▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ 266                  │
    (2.0,3.0]│▪▪▪▪▪ 53                                     │
             └─────────────────────────────────────────────┘
```

I was thinking of a vertical version, but it seems like it could be kind of space inefficient. Anyway, thought I'd share this for now.

**Comment by Evizero** [comment]
Hi! 

Well I have been thinking about histograms actually. 

I found some Unicode symbols (▖▗▘▙▚▛▜▝▞▟) that would be good for vertical ones as they are a denser pixel-grid and don't have spaces between them (in contrast to the Braille ones). So they would be nice and connected. Haven't gotten around to implementing the Canvas yet though.

But maybe that is an overkill for simple terminal plotting. Your approach seems much more reasonable; especially considering the labels. Horizontal would at least be a good intermediate solution

**Comment by IainNZ** [comment]
Yeah this is certainly a good starting point. I haven't looked into how this pacakge actually works yet. But, its something I'd be interested in helping with. Its not quite as pretty for me (maybe iTerm's fault?) but its still quite aesthetically pleasing

**Comment by Evizero** [comment]
Cool! well I would wait a little anyways, because I'm in the process of re-factoring. Where I could probably use some help after the refactoring is for spotting performance issues that can easily be avoided. For example, I had a huge performance gain by switching from `max(values...)` to `maximum(values)`. I'm still new to the language so things like this are prone to happen to me

Yes in #3 it was mentioned that the linespacing of iTerm ruins the illusion a bit. I don't use iTerm so I can't really say whats up there. Maybe there is a setting where the linespacing can be switched off or reduced(?)

**Comment by Evizero** [comment]
So I fixed a little detail concerning the bin-width, but now I have some floating point ugliness. Do you have ideas how to deal with this gracefully?

```Julia
function histogram(x, n::Int=5; args...)
    edges, counts = hist(x,n)
    labels = String[]
    binwidth = (edges.step - edges.start) / edges.divisor
    for i in 1:length(counts)
        push!(labels, string("(",edges[i],",",edges[i]+binwidth,"]"))
    end
    barplot(labels, counts; args...)
end
```

![hist](https://cloud.githubusercontent.com/assets/10854026/9342803/35b87a94-45fe-11e5-8974-91e38424b34e.png)

**Comment by IainNZ** [comment]
Ahh yeah thats rough. I wonder how Gadfly gets around it.

**Comment by Evizero** [comment]
I'll figure it out, but I think it'll turn out pretty well. They will be included in the soonish version update

![](https://raw.githubusercontent.com/Evizero/UnicodePlots.jl/api_refactor/doc/img/hist.png)
