### ISSUE TITLE
Stem Leaf Plot

### ISSUE THREAD

**Issue by alexhallam** [Evizero/UnicodePlots.jl#61]
How would you feel about adding a stem leaf plot? I think that with some changes to the `barplot` function we can have a sensible stem leaf plot. 

One issue is that `symb` only takes one character. It would have to be changed to allow integers. 

![screen shot 2016-12-15 at 1 59 29 pm](https://cloud.githubusercontent.com/assets/9298693/21243779/41c4db44-c2cf-11e6-8df0-b49f89d7e6b6.png)

**Comment by Evizero** [comment]
Sure. While I don't think the barplot is the right place for it, I do agree that it shouldn't be a problem supporting a terminal version of that plot. I don't think I would get around to it in the near future as a lot of tasks piled up that I want to finish first, but I'd happily review a PR

**Comment by alexhallam** [comment]
No problem. I will try a few things out and submit a PR.
