### ISSUE TITLE
ERROR: LoadError: LoadError: syntax: invalid type signature

### ISSUE THREAD

**Issue by memoiry** [Evizero/UnicodePlots.jl#65]
Hi

I have received this error when Julia> using UnicodePlots.jl

It follows

```
julia> using UnicodePlots
INFO: Precompiling module UnicodePlots.
ERROR: LoadError: LoadError: syntax: invalid type signature
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/pkgs-0.5.0.4/v0.5/UnicodePlots/src/canvas.jl, in expression starting on line 1
while loading /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/pkgs-0.5.0.4/v0.5/UnicodePlots/src/UnicodePlots.jl, in expression starting on line 51
ERROR: Failed to precompile UnicodePlots to /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/pkgs-0.5.0.4/lib/v0.5/UnicodePlots.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
```

**Comment by memoiry** [comment]
It there any way to fix it ? Thanks!

**Comment by Evizero** [comment]
I can't reproduce this in Julia 0.5. Maybe it has something to do with the package versions in Julia Pro? Sorry to say that I have never tried it

**Comment by myusufkocyigit** [comment]
I have the same error using StaticArrays. Any ways to fix it? 

julia> using StaticArrays
INFO: Precompiling module StaticArrays.
ERROR: LoadError: syntax: invalid type signature
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in anonymous at ./<missing>:2
 in eval(::Module, ::Any) at ./boot.jl:236
 in process_options(::Base.JLOptions) at ./client.jl:248
 in _start() at ./client.jl:335
while loading /home/muhammed/.julia/v0.6/StaticArrays/src/StaticArrays.jl, in expression starting on line 30
ERROR: Failed to precompile StaticArrays to /home/muhammed/.julia/lib/v0.6/StaticArrays.ji.
 in compilecache(::String) at ./loading.jl:672
 in require(::Symbol) at ./loading.jl:453

**Comment by Evizero** [comment]
I am afraid not, @myusufkocyigit . This seems to be unrelated to UnicodePlots. 

You could try asking in one of the following places

- https://github.com/JuliaArrays/StaticArrays.jl/issues
- https://discourse.julialang.org/
