### ISSUE TITLE
Not compatible with Travis's log

### ISSUE THREAD

**Issue by xukai92** [Evizero/UnicodePlots.jl#66]
See plots starting from Line 4300 of this Travis log: https://travis-ci.org/yebai/Turing.jl/jobs/224394352

The horizontal spacing seems weird and there is also some unknown characters.

**Comment by Evizero** [comment]
Yes, I have noticed that before. Not sure what I can do about it.

**Comment by xukai92** [comment]
Do you think I can work around the problem using the canvas? I'm looking into it but not quite sure how to use the ASCII one

**Comment by xukai92** [comment]
Or is there way to set the default canvas to ASCII?

**Comment by Evizero** [comment]
Try adding `canvas = DotCanvas` to every plot function.

**Comment by Evizero** [comment]
> Or is there way to set the default canvas to ASCII

No, I am afraid not

**Comment by xukai92** [comment]
It works! Many thanks!
