### ISSUE TITLE
filter deprecated warning

### ISSUE THREAD

**Issue by alanedelman** [Evizero/UnicodePlots.jl#67]
julia> unicodeplots()
Plots.UnicodePlotsBackend()

julia> plot( rand(3))
WARNING: filter(flt, itr) is deprecated, use Iterators.filter(flt, itr) instead.

**Comment by Evizero** [comment]
This sounds like a Plots.jl issue. I don't think `filter` is even in use in UnicodePlots itself

**Comment by Evizero** [comment]
I think this is fixed
