### ISSUE TITLE
plans for logarithmic histogram axes?

### ISSUE THREAD

**Issue by ExpandingMan** [Evizero/UnicodePlots.jl#71]
Hello all.  I'm absolutely loving this package, it's kind of blowing my mind how often pure unicode is totally and completely adequate for plotting.

Anyway, the one really major thing that I find to be lacking is logarithmic scales.  Are there any plans for this?  If not, I'd like to eventually do a PR for this after I spend some time digging through the source code.

**Comment by Evizero** [comment]
it wasn't on my radar but I'll keep it in mind. I am writing on the next generation of UnicodePlots, which I plan to release around New Year's. I may just add this as a priority item given that it influences basic design decisions quite a bit.

**Comment by ExpandingMan** [comment]
Great, I really look forward to the new version.

Speaking for myself at least, having the ability to do log scales is *extremely* important.  For me, it makes the difference between this being a fun tool that is convenient to use sometimes and it being a vital part of my workflow.  I suspect if you ask around on discourse you will find there are quite a few people for whom log scales are extremely important.

Thanks for all your great work on this package.

**Comment by CarloLucibello** [comment]
+1 for this feature

**Comment by Evizero** [comment]
on master
