### ISSUE TITLE
Support for other AbstractArray

### ISSUE THREAD

**Issue by juliohm** [Evizero/UnicodePlots.jl#73]
Thanks for the package, it is awesome. I tried to create a barplot today with a `MVector` containing the values and realized that the function are only defined in terms of `Vector`. Would it be a good idea to generalize the signature of the plot commands to work with any `AbstractArray` or `AbstractVector`?

**Comment by Evizero** [comment]
Right. A lot of old code around actually that needs some love in that respect. That said its unlikely to happen before 0.7. I would merge a quick fix if its not intrusive (e.g. no-brainers like changing from `::Vector` to `::AbstractVector`). The lack of formal tests make it difficult to judge bigger changes.

**Comment by juliohm** [comment]
Awesome, will submit a PR :+1:
