### ISSUE TITLE
Calling histogram within a function

### ISSUE THREAD

**Issue by edljk** [Evizero/UnicodePlots.jl#78]
Strangely, the call to
```julia
function callhist(n::Int64 = 10)
    UnicodePlots.histogram(randn(n))
    u = 1
end
```
does not produce any output. Erasing the last line `u = 1`, produces the expected histogram..

**Comment by Evizero** [comment]
That is because the commands themselves don't print the plot. Instead they create a `Plot` type, who's `show` method prints what you see.
