### ISSUE TITLE
color = :black ? color = :autobw ?

### ISSUE THREAD

**Issue by Datseris** [Evizero/UnicodePlots.jl#97]
How come that the option for the color to be black does not exist?

Also, can there be a setting `:autobw` that automatically uses black or white depending on whether the background is black or white? I had the default `:white` (by the way the option `:white` is not listed in README) and I noticed that in Jupyter it is very hard to see.

**Comment by Evizero** [comment]
`color = :normal` should now work on `master`. thiss will usually be white on a black background and black on a white background depending on terminal settings.
